services:
    rpi_imagegen:
        build: .
        privileged: true
        stdin_open: true
        tty: true
        image: rpi-imagegen:latest
        volumes:
            - ./surgeyos:/home/imagegen/surgeyos
            - ./image-build.sh:/home/imagegen/image-build.sh
            - rpi_imagegen_work:/home/imagegen/work
        env_file:
            - ./.env

volumes:
    rpi_imagegen_work:
